//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatPhong
    {
        public string MaDatPhong { get; set; }
        public string MaPhong { get; set; }
        public string MaKhachHang { get; set; }
        public System.DateTime NgayNhanPhong { get; set; }
        public System.DateTime NgayTraPhong { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
