//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.ChiTietPhongs = new HashSet<ChiTietPhong>();
            this.DatPhongs = new HashSet<DatPhong>();
        }
    
        public string MaPhong { get; set; }
        public string MaLoai { get; set; }
        public string MaTrangThai { get; set; }
        public string MaTrangThaiDonDep { get; set; }
        public string MaKhachHang { get; set; }
        public decimal Gia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhong> ChiTietPhongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatPhong> DatPhongs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
        public virtual TrangThaiPhong TrangThaiPhong { get; set; }
        public virtual TrangThaiDonDep TrangThaiDonDep { get; set; }
    }
}
